import { HOUSE_LINKS } from "./houseLinks";

export const HOUSE_CONFIG = {
  jael: {
    name: "Tribe Jael",
    colorName: "Red",
    whatsapp: HOUSE_LINKS.jael,
    emoji: "⚔️",
    image: "",
    bannerImage: "",
    color: "bg-red-600 text-white border-red-700",
    gradient: "from-red-600 to-rose-700",
    hex: "#DC2626",
    theme: "courage",
    accentColor: "red",
    tagline: "Bold Courage & Victory",
  },
  abigail: {
    name: "Tribe Abigail",
    colorName: "Green",
    whatsapp: HOUSE_LINKS.abigail,
    emoji: "🕊️",
    image: "",
    bannerImage: "",
    color: "bg-green-600 text-white border-green-700",
    gradient: "from-emerald-600 to-green-700",
    hex: "#16A34A",
    theme: "wisdom",
    accentColor: "green",
    tagline: "Wisdom, Peace & Grace",
  },
  esther: {
    name: "Tribe Esther",
    colorName: "Purple",
    whatsapp: HOUSE_LINKS.esther,
    emoji: "👑",
    image: "",
    bannerImage: "",
    color: "bg-purple-600 text-white border-purple-700",
    gradient: "from-purple-600 to-fuchsia-700",
    hex: "#9333EA",
    theme: "royalty",
    accentColor: "purple",
    tagline: "Royalty, Favor & Purpose",
  },
  deborah: {
    name: "Tribe Deborah",
    colorName: "Blue",
    whatsapp: HOUSE_LINKS.deborah,
    emoji: "⚖️",
    image: "",
    bannerImage: "",
    color: "bg-blue-600 text-white border-blue-700",
    gradient: "from-blue-600 to-indigo-700",
    hex: "#2563EB",
    theme: "leadership",
    accentColor: "blue",
    tagline: "Visionary Leadership & Strength",
  },
  priscilla: {
    name: "Tribe Priscilla",
    colorName: "Pink",
    whatsapp: HOUSE_LINKS.priscilla,
    emoji: "🌸",
    image: "",
    bannerImage: "",
    color: "bg-pink-600 text-white border-pink-700",
    gradient: "from-pink-500 to-rose-600",
    hex: "#DB2777",
    theme: "devotion",
    accentColor: "pink",
    tagline: "Devotion, Love & Hospitality",
  },
} as const;

export type HouseType = keyof typeof HOUSE_CONFIG;

export const PRIMARY_HOUSES: HouseType[] = [
  "jael",
  "abigail",
  "esther",
  "deborah",
  "priscilla",
];

