import { HOUSE_LINKS } from "./houseLinks";

export const HOUSE_CONFIG = {
  jael: {
    name: "Tribe Jael",
    colorName: "Red",
    whatsapp: HOUSE_LINKS.jael,
    emoji: "⚔️",
    image: "",
    bannerImage: "",
    color: "bg-red-600 text-white border-red-700",
    gradient: "from-red-600 to-rose-700",
    hex: "#DC2626",
    theme: "courage",
    accentColor: "red",
    tagline: "Bold Courage & Victory",
  },
  abigail: {
    name: "Tribe Abigail",
    colorName: "Green",
    whatsapp: HOUSE_LINKS.abigail,
    emoji: "🕊️",
    image: "",
    bannerImage: "",
    color: "bg-green-600 text-white border-green-700",
    gradient: "from-emerald-600 to-green-700",
    hex: "#16A34A",
    theme: "wisdom",
    accentColor: "green",
    tagline: "Wisdom, Peace & Grace",
  },
  esther: {
    name: "Tribe Esther",
    colorName: "Purple",
    whatsapp: HOUSE_LINKS.esther,
    emoji: "👑",
    image: "",
    bannerImage: "",
    color: "bg-purple-600 text-white border-purple-700",
    gradient: "from-purple-600 to-fuchsia-700",
    hex: "#9333EA",
    theme: "royalty",
    accentColor: "purple",
    tagline: "Royalty, Favor & Purpose",
  },
  deborah: {
    name: "Tribe Deborah",
    colorName: "Blue",
    whatsapp: HOUSE_LINKS.deborah,
    emoji: "⚖️",
    image: "",
    bannerImage: "",
    color: "bg-blue-600 text-white border-blue-700",
    gradient: "from-blue-600 to-indigo-700",
    hex: "#2563EB",
    theme: "leadership",
    accentColor: "blue",
    tagline: "Visionary Leadership & Strength",
  },
  priscilla: {
    name: "Tribe Priscilla",
    colorName: "Pink",
    whatsapp: HOUSE_LINKS.priscilla,
    emoji: "🌸",
    image: "",
    bannerImage: "",
    color: "bg-pink-600 text-white border-pink-700",
    gradient: "from-pink-500 to-rose-600",
    hex: "#DB2777",
    theme: "devotion",
    accentColor: "pink",
    tagline: "Devotion, Love & Hospitality",
  },
  // Legacy aliases for historical DB data compatibility
  stark: {
    name: "House Stark",
    colorName: "Grey",
    whatsapp: HOUSE_LINKS.stark,
    emoji: "🐺",
    image: "/images/stark (10).jpeg",
    bannerImage: "/images/stark (10).jpeg",
    color: "bg-stark text-white border-stark-dark",
    gradient: "from-slate-300 to-slate-400",
    hex: "#94A3B8",
    theme: "snow",
    accentColor: "slate",
    tagline: "Winter is Coming",
  },
  baratheon: {
    name: "House Baratheon",
    colorName: "Gold",
    whatsapp: HOUSE_LINKS.baratheon,
    emoji: "🦌",
    image: "/images/House Baratheon Logo PNG Vector (AI) Free Download.jpeg",
    bannerImage: "/images/House Baratheon Logo PNG Vector (AI) Free Download.jpeg",
    color: "bg-baratheon text-gray-900 border-baratheon-dark",
    gradient: "from-amber-300 to-amber-400",
    hex: "#FBBF24",
    theme: "lightning",
    accentColor: "amber",
    tagline: "Ours is the Fury",
  },
  greyjoy: {
    name: "House Greyjoy",
    colorName: "Black",
    whatsapp: HOUSE_LINKS.greyjoy,
    emoji: "🐙",
    image: "/images/House Greyjoy of Pyke Sigil (1X1 Version) (1).jpeg",
    bannerImage: "/images/House Greyjoy of Pyke Sigil (1X1 Version) (1).jpeg",
    color: "bg-greyjoy text-white border-greyjoy-dark",
    gradient: "from-slate-800 to-slate-900",
    hex: "#1E293B",
    theme: "waves",
    accentColor: "slate",
    tagline: "We Do Not Sow",
  },
  lannister: {
    name: "House Lannister",
    colorName: "Crimson",
    whatsapp: HOUSE_LINKS.lannister,
    emoji: "🦁",
    image: "/images/House Lannister.jpeg",
    bannerImage: "/images/House Lannister.jpeg",
    color: "bg-lannister text-white border-lannister-dark",
    gradient: "from-red-600 to-red-700",
    hex: "#DC2626",
    theme: "lion",
    accentColor: "red",
    tagline: "Hear Me Roar",
  },
  targaryen: {
    name: "House Targaryen",
    colorName: "Fire",
    whatsapp: HOUSE_LINKS.targaryen,
    emoji: "🐉",
    image: "/images/House Targaryen.jpeg",
    bannerImage: "/images/House Targaryen.jpeg",
    color: "bg-targaryen text-white border-targaryen-dark",
    gradient: "from-rose-500 to-rose-600",
    hex: "#F43F5E",
    theme: "fire",
    accentColor: "rose",
    tagline: "Fire and Blood",
  },
} as const;

export type HouseType = keyof typeof HOUSE_CONFIG;

export const PRIMARY_HOUSES: HouseType[] = [
  "jael",
  "abigail",
  "esther",
  "deborah",
  "priscilla",
];

